# FX AI Bot Configuration Example
# Copy this file to config.yaml and modify as needed.
symbols: ["EURUSD","GBPUSD","USDJPY","AUDUSD","USDCHF"]
timeframes: ["M5"]
risk:
  max_risk_per_trade_bps: 100
  stop_atr_mult: 1.8
  takeprofit_atr_mult: 2.6
  kill_switch:
    max_intraday_drawdown_pct: 2.0
    max_daily_trades_per_symbol: 6
trading_window:
  enabled: true
  start_hour_utc: 6
  end_hour_utc: 20
alerts:
  telegram_enabled: true
  telegram_bot_token_env: "TELEGRAM_BOT_TOKEN"
  telegram_chat_id_env: "TELEGRAM_CHAT_ID"
news:
  enabled: true
  news_api_key_env: "NEWS_API_KEY"
  keywords: ["forex", "currency", "central bank", "interest rates", "inflation", "GDP", "fed", "ecb"]
  sources: [] # Optional: e.g., ["reuters", "bloomberg"]
fundamental:
  enabled: true
  importances: ["high", "medium"] # high, medium, low
