broker:
  name: MT5

symbols: ["EURUSD","GBPUSD","USDJPY"]   # keep it to 3 tight pairs

timeframes: ["M5"]        # M5 only

risk:
  max_risk_per_trade_bps: 80           # 0.8% of equity per trade, fewer skips
  stop_atr_mult: 2.0                   # a bit wider SL, lets trades breathe
  takeprofit_atr_mult: 3.0             # wider TP, aiming for ~1:1.5 RR
  
  kill_switch:
    max_intraday_drawdown_pct: 4.0     # give bot room for volatility
    max_daily_trades_per_symbol: 6

trading_window:
  enabled: true
  start_hour_utc: 6                    # London open-ish
  end_hour_utc: 20                     # London/NY overlap

strategy:
  # How long to keep a position before we even consider closing (minutes)
  min_hold_min: 30

  # Confidence threshold to EXIT early after min_hold_min has passed
  # Lower = requires a stronger reversal to close (0.45 is stricter than 0.55)
  exit_thresh: 0.45

  # (Optional) If you want to tweak these via config too:
  enter_thresh: 0.62
  cooldown_min: 10


alerts:
  telegram_enabled: true
  telegram_bot_token_env: "TELEGRAM_BOT_TOKEN"
  telegram_chat_id_env: "TELEGRAM_CHAT_ID"

costs:
  spread_bps_default: 1.2
